apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: video-processor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"  # Always have at least 1 instance running
        autoscaling.knative.dev/maxScale: "10" # Scale up to 10 instances max
        run.googleapis.com/cpu-throttling: "false" # Disable CPU throttling for video processing
    spec:
      containerConcurrency: 30 # Maximum number of concurrent requests per container
      timeoutSeconds: 1800 # 30 minutes max request processing time
      containers:
        - image: gcr.io/PROJECT_ID/video-processor:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            # Database Configuration
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: video-processor-secrets
                  key: database_url

            # Supabase Configuration
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: video-processor-secrets
                  key: supabase_url
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: video-processor-secrets
                  key: supabase_service_role_key
            - name: SUPABASE_BUCKET_NAME
              value: "processed-videos"
              
            # Proxy Configuration (optional)
            - name: USE_PROXY
              value: "true"
            - name: WEBSHARE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: video-processor-secrets
                  key: webshare_username
                  optional: true
            - name: WEBSHARE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: video-processor-secrets
                  key: webshare_password
                  optional: true
                  
            # Video Processing Configuration
            - name: VIDEO_DOWNLOAD_DIR
              value: "/tmp/video_downloads"
            - name: MAX_FILE_SIZE
              value: "1073741824" # 1GB max file size
            - name: VIDEO_QUALITY
              value: "best[height<=720]/best"
              
            # Download Optimization - aria2c and direct streaming
            - name: USE_ARIA2C
              value: "true"
            - name: USE_DIRECT_PROCESSING
              value: "true"
            
            # Timeout Configuration
            - name: INFO_EXTRACTION_TIMEOUT
              value: "300" # 5 minutes
            - name: DOWNLOAD_TIMEOUT
              value: "900" # 15 minutes
            - name: UPLOAD_TIMEOUT
              value: "600" # 10 minutes
              
            # Logging Configuration
            - name: LOG_LEVEL
              value: "INFO"
              
          # Health check settings
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
